map:
  width: 25.0         # Ширина цеха в метрах
  height: 20.0        # Высота цеха в метрах
  resolution: 0.025   # Размер одной ячейки (2.5 см)

robot:
  # Габариты из ТЗ (1000x700 мм)
  length: 1.0         # Длина в метрах
  width: 0.7          # Ширина в метрах

  # Радиус описанной окружности (половина от диаметра разворота 1100 мм)
  # Используется для слоя инфляции (inflation_radius) при глобальном планировании
  circumscribed_radius: 0.55

  # Динамические ограничения
  max_speed: 5.0      # Максимальная линейная скорость (м/с) по ТЗ
  max_yaw_rate: 1.0   # Максимальная угловая скорость (рад/с) - оставляем стандартной

navigation:
  xy_goal_tolerance: 0.005  # Требуемая точность позиционирования (5 мм)
  yaw_goal_tolerance: 0.05  # Точность угла поворота (рад)

points:
    # Точки погрузки деталей (красные зоны)
  loading:
      - [ 2.0, 5.0 ]
      - [ 2.0, 8.0 ]
      - [ 2.0, 11.0 ]
      - [ 2.0, 14.0 ]
      - [ 2.0, 17.0 ]

    # Рабочие станции / точки разгрузки (зеленые зоны)
  workstations:
      - [ 22.0, 5.0 ]
      - [ 22.0, 8.0 ]
      - [ 22.0, 11.0 ]
      - [ 22.0, 14.0 ]
      - [ 22.0, 17.0 ]

    # Склад готовой продукции (синяя зона)
  delivery:
      - [ 22.0, 2.0 ]

    # Станция зарядки (желтая зона)
  charging:
      - [ 2.0, 2.0 ]